#!/bin/bash
source $(dirname $0)/.include

if $BASEDIR/dev-bin/is-jekyll-running; then
  echo "Jekyll is already running"
  exit 1
fi

( bundle exec jekyll serve 2>&1 & echo $! >&3 ) 3> $PIDFILE | tee -a $BASEDIR/run/jekyll.out &
